replicaCount: 1

image:
  repository: venkyy82/hcl_hackathon
  tag: "Patient.${{ github.run_number }}"
  pullPolicy: IfNotPresent

service:
  name: patient-service
  type: ClusterIP
  port: 80

ingress:
  enabled: false
