name: Terraform AKS

on:
  workflow_dispatch: # manual trigger or change to push if needed

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TERRAFORM_WORKDIR: ./Terraform  # Set your Terraform directory here

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.7.0

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init $TERRAFORM_WORKDIR

    - name: Terraform Plan
      run: terraform plan -out=tfplan $TERRAFORM_WORKDIR

    - name: Terraform Apply
      run: terraform apply -auto-approve $TERRAFORM_WORKDIR/tfplan
